name: 🤖 Android Builds
on:
  workflow_call:

# Global Settings
env:
  SCONS_FLAGS: >-
    dev_mode=yes
    module_text_server_fb_enabled=yes
    tests=no
    swappy=yes

jobs:
  build-android:
    runs-on: ubuntu-24.04
    name: ${{ matrix.name }}
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Editor (target=editor)
            cache-name: android-editor
            target: editor
            scons-flags: >-
              arch=arm64
              production=yes

          - name: Template arm32 (target=template_release, arch=arm32)
            cache-name: android-template-arm32
            target: template_release
            scons-flags: arch=arm32

          - name: Template arm64 (target=template_release, arch=arm64)
            cache-name: android-template-arm64
            target: template_release
